### ISSUE TITLE
redirect after do-login.js

### ISSUE THREAD

**Issue by wojtulab** [jixunmoe/meross-login#1]
Hello,
I can't properly get my key.

Every time I am getting the same:
`{
  apiStatus: 1030,
  sysStatus: 0,
  data: {
    domain: 'https://eu-iot.meross.com',
    mqttDomain: 'mqtt-eu-2.meross.com'
  },
  info: 'redirect app to login other than this region',
  timeStamp: 1638190031
}
`

I am from europe, so src/utils/remoteAPI.js line with **remoteBase**  changed as following
 accountCountryCode = 'EU';
 remoteBase = "https://eu-iot.meross.com/";

I can't repair it. Could you help me?

**Comment by jixunmoe** [comment]
Did a refactor for the CLI script, it now supports region selection (currently only `US` and `EU`).

Please pull latest change and give this a try:

```sh
node meross login --region EU "my_email@example.com" "my_secret_password"
```

Let me know if this change works for you 😎

**Comment by wojtulab** [comment]
ok thanks, another issue:
```
`bash-5.0# node meross generate-config
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /usr/src/node-red/tmp/meross-login/src/bin/meross.js
- /usr/src/node-red/tmp/meross-login/meross
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/src/node-red/tmp/meross-login/src/bin/meross.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/node-red/tmp/meross-login/src/bin/meross.js',
    '/usr/src/node-red/tmp/meross-login/meross'
  ]
}
bash-5.0#
bash-5.0# ls /usr/src/node-red/tmp/meross-login/src/bin/meross.js
/usr/src/node-red/tmp/meross-login/src/bin/meross.js
bash-5.0#
bash-5.0# ls /usr/src/node-red/tmp/meross-login/src/bin/meross.js -l
-rw-r--r--    1 node-red node-red      1007 Nov 30 08:24 /usr/src/node-red/tmp/meross-login/src/bin/meross.js`
```

**Comment by jixunmoe** [comment]
Please reinstall dependencies, as I've added a new package to parse command line arguments properly...

You can use `npm ci --prod` to do so.

Let me know if you have any other issues.

**Comment by wojtulab** [comment]
it's working!!!! thanks dude
I made workaround with IFTTT but meross-login package is awesome.

![image](https://user-images.githubusercontent.com/14801148/144064497-18ddfcec-5791-49be-90e9-e2bf341b2776.png)

Have a greate day and thanks again :)
