### ISSUE TITLE
Probably dumb question

### ISSUE THREAD

**Issue by scargill** [jixunmoe/meross-login#2]
Hi

I installed node-red-contrib-meross (I have 3 meross smart plugs). I came here to try this login - fails - am i missing something? cannot find module /home/pi/meross....

**Comment by jixunmoe** [comment]
Hi,

To use this project, you'll need to:

- Install node (v16 via [nodesource](https://github.com/nodesource/distributions#debinstall) or [nvm](https://github.com/nvm-sh/nvm#installing-and-updating))
- Clone this repo (`git clone https://github.com/jixunmoe/meross-login.git`) or download the zip of latest commit and extract it to a directory;
- In the terminal, change to the repo directory, and run `npm ci --prod` to install dependencies.

Then, to get login token:

- Run `node meross generate-config` to generate a dummy mobile config (create a random android device)
- Run `node meross login --region EU "your-account-login-address" "your-password"`

... where region parameter can be [EU or US](https://github.com/jixunmoe/meross-login/blob/main/src/utils/apiRegion.js) depending on the account (you can try both)

If everything works, you should be able to see something like the following printed to the terminal:

```json
{
  "apiStatus": 0,
  "sysStatus": 0,
  "data": {
    "token": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "key": "ffffffffffffffffffffffffffffffff",
    "userid": "123456789",
    "email": "jixun.moe@your.email.com",
    "domain": "https://us-iot.meross.com",
    "mqttDomain": "mqtt-us.meross.com"
  },
  "info": "Success",
  "timeStamp": 123456789
}
```

If you experience any error, please copy / paste the entire command and the response (replace your email/password and anything sensitive with a `*`) so I can understand further where it went wrong.

**Comment by jixunmoe** [comment]
Closing issue as no response for a week.
